use_frameworks!

target 'JXPhotoSelector_Example' do
  pod 'JXPhotoSelector', :path => '../'

  target 'JXPhotoSelector_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
